### ISSUE TITLE
Il y a des "lien=" perdus...

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#10]
https://pratiques.vpspreprod.tripleperformance.fr/wiki/Implanter_des_haies

  Application de la technique à...
  lien=
  
  Toutes les cultures :
  Facilement généralisable

**Comment by bertrandgorge** [comment]
En fait c'est les smiley... Attention il manque le image: (et de manière générale c'est mieux de mettre le code en anglais) : 

   [[smiley_upface.png|lien=]]

==>

   [[image:smiley_upface.png|link=]]

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
Ok - je garde ouvert car il faut charger les images en question

**Comment by bertrandgorge** [comment]
Done via le template (voir issue #16)
