### ISSUE TITLE
La rubrique "Pour en savoir plus" mériterait des bullet points devant chaque ligne

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#11]
https://pratiques.vpspreprod.tripleperformance.fr/index.php?title=Pratiquer_les_techniques_culturales_sans_labour_(TCSL)&action=edit&section=40

A voir si c'est possible sans être trop compliqué

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
Parfait !
