### ISSUE TITLE
Le caption de l'image n'est pas bon

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#12]
https://pratiques.tripleperformance.fr/wiki/Pratiquer_la_lutte_biologique_%C3%A0_l%27aide_de_microorganismes --> Smiley_upface.png

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
Hum - le résultat c'est qu'on a plus l'image ! https://pratiques.vpspreprod.tripleperformance.fr/wiki/Pratiquer_la_lutte_biologique_%C3%A0_l%27aide_de_microorganismes

**Comment by LoicJel** [comment]
Le problème venait de la modification des templates, c'est réglé !

**Comment by bertrandgorge** [comment]
Pas encore - il manque l'image https://geco.ecophytopic.fr/documents/20182/21720/image_Pratiquer_la_lutte_biologique___l_aide_de_microorganismes.jpg ?
