### ISSUE TITLE
Placer toutes les catégories dans des templates, autant que possible

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#13]
Il faudrait s'assurer que les catégories type [[Category:exempleMiseEnOeuvre]] ne soient pas mis direct dans les pages mais dans les templates type {{exempleMiseEnOeuvre}}

Au passage, ça vaut le coup de renommer les templates pour lire {{Exemple de mise en oeuvre}} (au singulier)
Et la catégorie : [[Category:=Exemples de mise en oeuvre]] (au pluriel)

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
OK
