### ISSUE TITLE
L'image importée de wikipedia est parfois vide

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#15]
Par exemple dans https://pratiques.vpspreprod.tripleperformance.fr/wiki/Crosne 👍 

`[[file:|thumb|Crosne]]`

**Comment by bertrandgorge** [comment]
Apparemment c'est parce que la page wikipedia associée est une page d'homonymie : https://fr.wikipedia.org/wiki/Crosne

**Comment by bertrandgorge** [comment]
Il faut peut-être utiliser https://fr.wikipedia.org/w/api.php?action=query&prop=categories&titles=Crosne&clcategories=Category:Homonymie pour vérifier que la page en question n'est pas une page d'homonymie

**Comment by LoicJel** [comment]
Fait !
