### ISSUE TITLE
La catégorie "Informations importé de GECO" doit être ajoutée par le template ThanksGeco

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#2]
Aujourd'hui la catégorie est ajoutée en dur dans chaque article

https://pratiques.vpspreprod.tripleperformance.fr/index.php?title=Mod%C3%A8le:ThanksGeco&action=edit

https://pratiques.vpspreprod.tripleperformance.fr/index.php?title=Cat%C3%A9gorie:Informations_import%C3%A9_de_GECO&action=edit&redlink=1

**Comment by LoicJel** [comment]
c'est fait
