### ISSUE TITLE
Les caractères spéciaux ne sont pas remplacés dans les redirections

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#21]
https://pratiques.tripleperformance.fr/index.php?title=Basique&action=edit

Dans cette page on a une redirection vers [[Basique (pH > 7,5)]] alors que la vraie page s'appelle [[Basique (pH supérieur à 7,5)]]

**Comment by LoicJel** [comment]
Fait !
voir le commit suivant : 
https://github.com/LoicJel/wiki_builder/commit/e9d4d3ef5e7cd00804ffd4fde539565826ee6251

**Comment by bertrandgorge** [comment]
Parfait
