### ISSUE TITLE
Les images dont le nom est en md5 ne sont pas correctement affichées

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#22]
Dans la page : https://pratiques.tripleperformance.fr/wiki/Tordeuse_du_pois

on a ce code : 

`[[197460ae78d107d1d746f89c79983ba2.jpg|lien=|alt=|756x756px]]  
[[1b6661510934fbb87b66ed476c4dd661.jpg|lien=|alt=|306x306px]]`

Dans lequel il manque le [[image:....]]

Voir les erreurs là : https://pratiques.tripleperformance.fr/wiki/Sp%C3%A9cial:Pages_demand%C3%A9es

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
Parfait
