### ISSUE TITLE
Redirection sur soi-même

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#23]
Il y a quelques redirections qui pointent sur elles-mêmes : https://pratiques.tripleperformance.fr/index.php?title=Botrytis_cinerea&redirect=no (NB sachant qu'il y a une redirection de la catégorie aussi vers cette même page : https://pratiques.tripleperformance.fr/index.php?title=Cat%C3%A9gorie:Artemisia_vulgaris&redirect=no)

La liste des doubles redirections est là : https://pratiques.tripleperformance.fr/wiki/Sp%C3%A9cial:Doubles_redirections

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
Parfait
