### ISSUE TITLE
Il faut laisser un espace entre l'introduction de wikipedia et le __TOC__

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#3]
Voir : https://pratiques.vpspreprod.tripleperformance.fr/wiki/Vers_de_terre

**Comment by LoicJel** [comment]
c'est fait !

**Comment by bertrandgorge** [comment]
Je laisse ouvert. Ce serait bien d'ajouter deux espaces en fait. Si on n'en met qu'un ça fait que le texte est collé au TOC.

Mais finalement, pourquoi mettre spécifiquement le __TOC__ à cet endroit ? On peut le supprimer non ?

**Comment by LoicJel** [comment]
Le __TOC__ a été enlevé du script

**Comment by bertrandgorge** [comment]
ok
