### ISSUE TITLE
Fusionner les templates "context" dans "Exemple de mise en oeuvre"

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#36]
ex : https://wiki.tripleperformance.fr/index.php?title=Faux-semis_scalpeur_pour_lutter_contre_les_chardons_en_d%C3%A9sherbage_m%C3%A9canique_(Damien_Carpene_-_Aglae)&action=edit

{{context|département=32|nom du département= [[Gers (32)]]|texture=Argilo-calcaire}}
{{Exemple de mise en oeuvre
|Nom=Mise en oeuvre d'un faux-semis scalpeur
|Image=Damien Carpene - Faux-semis Scalpeur.jpg
|Organisme=Chambre d'Agriculture Occitanie
|Programme=Aglae
|Auteur=Damien Carpene
|Année de mise en place=2016 }}

Ne garder que : 

{{Exemple de mise en oeuvre
|Nom=Mise en oeuvre d'un faux-semis scalpeur
|Image=Damien Carpene - Faux-semis Scalpeur.jpg
|Organisme=Chambre d'Agriculture Occitanie
|Programme=Aglae
|Auteur=Damien Carpene
|Année de mise en place=2016 
|département=32
|nom du département= [[Gers (32)]]
|texture=Argilo-calcaire }}

**Comment by LoicJel** [comment]
fait !
