### ISSUE TITLE
Agrifind : renommer les titres des articles

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#39]
https://wiki.vpspreprod.tripleperformance.fr/wiki/Les_coccinelles --> https://wiki.vpspreprod.tripleperformance.fr/wiki/Coccinelles

A faire au niveau de l'excel ?

**Comment by LoicJel** [comment]
Oui c'est suffisant normalement.

**Comment by bertrandgorge** [comment]
Done dans l'excel
