### ISSUE TITLE
Agrifind: il manque les templates bioagresseurs, etc...

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#40]
ex : https://wiki.vpspreprod.tripleperformance.fr/wiki/Les_coccinelles
vs : https://wiki.vpspreprod.tripleperformance.fr/wiki/Coccinelles

**Comment by bertrandgorge** [comment]
Sachant que pour les pages qui traitent d'un bioagresseur lié à une espèce végétale en particulier, il faut préciser le template : 

Pour le bioagresseur : https://wiki.vpspreprod.tripleperformance.fr/wiki/Orobanche_rameuse

{{Bioagresseur
|Nom=Orobanche rameuse
|Latin=
|Sous-categorie=dicotylédones vivaces
|Image=Orobanche_ramosa2Torrevieja.jpg
|ImageCaption=Phelipanche ramosa
}}

Pour le bioagresseur sur une espèce : https://wiki.vpspreprod.tripleperformance.fr/wiki/Orobanche_sur_colza

{{Bioagresseur
|Nom=Orobanche rameuse
|Culture=Colza
|Sous-categorie=dicotylédones vivaces
|Image=CZH_Orobranche_1-min.jpg
|ImageCaption=
}}

**Comment by bertrandgorge** [comment]
CF colonnes D et E de l'excel https://docs.google.com/spreadsheets/d/15fKUKDlFGFDDy_Smi7uhIRS0Z9gvEnLx4iyv-u2L6P8/edit#gid=0

**Comment by LoicJel** [comment]
Fait !
