### ISSUE TITLE
Il manque un espace entre "pour plus de précision ..." et les titres suivants

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#7]
https://pratiques.vpspreprod.tripleperformance.fr/wiki/Acariens_pr%C3%A9dateurs

= Annexes =
{{ListingAnnexes|aPourFils=1}}
=== La prolifération de l'organisme est favorisé par les pratiques suivantes : ===
*[[Implanter des haies]]
*[[Pratiquer les techniques culturales sans labour (TCSL)]]

^^ Il manque un espace avant le titre de niveau 3

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
C'est good.
