### ISSUE TITLE
Le titre Annexes devrait être un titre de niveau 2 plutôt que de niveau 1

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/wiki_builder#8]
https://pratiques.vpspreprod.tripleperformance.fr/wiki/Acariens_pr%C3%A9dateurs

= Annexes =
{{ListingAnnexes|aPourFils=1}}

==>

== Annexes ==
{{ListingAnnexes|aPourFils=1}}

**Comment by LoicJel** [comment]
Fait !

**Comment by bertrandgorge** [comment]
Vérifié
